version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app-docker:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
volumes:
  db_data:
